### ISSUE TITLE
rp crash with one of the sample files

### ISSUE THREAD

**Issue by bh1svr** [Austrian-Broadcasting-Services/obeca-info#2]
Hello.
I tried the program with one of the sample files which is downloaded from wiki. The file name is 10MHz_MCS26_HLS_q4a_1.2.raw.
![image](https://user-images.githubusercontent.com/42603585/118360484-68b26b80-b5ba-11eb-88b7-ee289166a848.png)
The last row of output means "Segmentation Fault (Core dumped)". 
I tried to run it as root, the result is the same.
If you need the dumped file, I can try to provide it.

**Comment by bh1svr** [comment]
debug the program using gdb. the crash happens at the following row:
![image](https://user-images.githubusercontent.com/42603585/118916337-52f9c900-b961-11eb-8a73-c50d11bff1c6.png)

**Comment by christophtanzer** [comment]
Hello bh1svr,

thank you for your question and sorry for the late reply.
Probably theree is an incompatibility with the version of the compiler or the operating system.

Would you please provide us with the output of the following commands so that we can further investigate your problem:
-	uname -a
-	lsb_release -a
-	gcc --version
-	apt show libc6 -a

thank you in advance

**Comment by stefanbabel** [comment]
Hello!

we are currently investigating this problem. 
Sample file "10MHz_MCS26_HLS_q4a_1.2.raw" works fine on our setup however (also downloaded from wiki). Does the segmentation fault only appear with this sample file or also with the others (especially these with 5 MHz bandwidth)?

We will let you know when we have found a solution to this.

**Comment by bh1svr** [comment]
Hello.

I have tried another file  10MHz_MCS9_HLS_q4a_1.2.raw. The result remains the same.
I have not tried files with 5MHz bandwidth. I will try it. This may causes some time, because of my poor network.

Thanks.

**Comment by bh1svr** [comment]
Hello,

I have tried 5MHz_MCS16_HLS_q4a_1.2.raw, It works fine. The issue may occur in 10M bandwith only.

**Comment by stefanbabel** [comment]
Hello,

interesting! Seems for me that your virtual machine can't handle that much data. 
How about the ressources on your virtual machine (CPU, CPU Cores, RAM, ...), do they match our hardware requirements (found in our wiki)?

**Comment by bh1svr** [comment]
Hello, 

My CPU is Intel Skylake i5 6200U，with 2 cores and 4 threads. My RAM is 8GB. I think it is below the hardware requirements.
