### ISSUE TITLE
Gateway and Receive process repositories are down 

### ISSUE THREAD

**Issue by mmzezi** [Austrian-Broadcasting-Services/obeca-info#3]
Can't access any of the aforementioned repositories on this page: https://github.com/Austrian-Broadcasting-Services/obeca-info/wiki

Were they removed or are they just down at the moment?

**Comment by stefanbabel** [comment]
Hello,
the OBECA project has been transferred to the 5G MAG Reference Tools (https://github.com/5G-MAG) a while ago.
The processes have also been renamed: 
- Receive Process -> rt-mbms-modem
- Gateway Process -> rt-mbms-mw

Futher developement takes place there. 
For more information have a look at the wiki: https://github.com/5G-MAG/Documentation-and-Architecture/wiki

**Comment by mmzezi** [comment]
Thank you and apologies for the meaningless issue!
